# This docker compose file is intended for developing
# concertim-cluster-builder.  It is *NOT* suitable for production usage.  See
# README.md for production installation instructions.
services:
  cluster_builder: 
    build:
      context: .

    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT

    ports:
      - '42378:42378'

    # Override the command in the Dockerfile to start add in the `--debug`
    # flag.  Is there a better way of appending a single argument?
    command: ["flask", "--app", "cluster_builder", "run", "-h", "0.0.0.0", "-p", "42378", "--debug"]

    # Mount `.` to `/app` to allow editing on the local and having flask automatically reload.
    volumes:
      - ./:/app

    # Use the same UID and GID as is used for the local user.  This prevents
    # issues with permissions for files in the mounted volume.
    #
    # If this setting is not suitable for you, use the
    # `docker-compose.override.yml` file to change it.  See
    # `docs/DEVELOPMENT.md` for details.
    user: "1000:1000"
