heat_template_version: 2021-04-16

parameters:
  clustername:
    type: string
    label: Cluster Name
    description: The name to give the cluster
    constraints:
      - length: {min: 6, max: 255}
        description: Cluster name must be between 6 and 255 characters
      - allowed_pattern: ^[a-zA-Z][a-zA-Z0-9\-_]*$
        description: Cluster name can contain only alphanumeric characters, hyphens
          and underscores

  external-network:
    type: string
    label: External Network Name
    description: The name of the external network to bridge network to
    default: public1
    constraints:
      - custom_constraint: neutron.network

  gateway-pri-ip:
    type: string
    label: Gateway Primary IP Address
    default: 10.100.0.101
    constraints:
      - custom_constraint: ip_addr

  gateway-flavour:
    type: string
    label: Gateway node flavour
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor

  key_name:
    type: string
    label: SSH KeyPair name
    description: Name of a KeyPair to enable SSH access to the cluster
    constraints:
      - custom_constraint: nova.keypair

  solo-image:
    type: string
    label: Flight Solo Image ID
    constraints:
      - custom_constraint: glance.image

  gateway-vol-size:
    type: number
    label: Size of the shared storage disk for NFS in GB
    default: 100
    constraints:
      - range: {min: 16, max: 100}
  access-password:
    type: string
    label: Password for the 'flight' user
    description: Enter the password to set for the 'flight' user.  You can use this
      to gain access to the cluster via Flight Web Suite
    hidden: true
    constraints:
      - length: {min: 6}
        description: The password must be at least 6 characters

resources:
  gateway-pri-port:
    type: OS::Neutron::Port
    depends_on: cluster-network-pri
    properties:
      name: {list_join: ['-', [gateway1, pri, get_param: clustername]]}
      network: {get_resource: cluster-network}
      security_groups:
        - {get_resource: cluster-sg}
      fixed_ips:
        - subnet: {get_resource: cluster-network-pri}
          ip_address: {get_param: gateway-pri-ip}

  gw:
    type: OS::Nova::Server
    properties:
      name: {list_join: [., [gateway1, get_param: clustername, alces.network]]}
      flavor: {get_param: gateway-flavour}
      key_name: {get_param: key_name}
      admin_user: flight
      networks:
        - port: {get_resource: gateway-pri-port}
      block_device_mapping_v2:
        - volume_id: {get_resource: gateway-vol}
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: {get_file: ../user_data/gateway.yaml}
          params:
            $clustername: {get_param: clustername}
            $nodename: gateway1
            $password: {get_param: access-password}

  gateway-vol:
    type: OS::Cinder::Volume
    properties:
      image: {get_param: solo-image}
      size: {get_param: gateway-vol-size}

  gateway-ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external-network}
      port_id: {get_resource: gateway-pri-port}

outputs:
  gateway_ext_ip:
    description: Gateway External IP
    value: {get_attr: [gateway-ip, floating_ip_address]}

