heat_template_version: 2021-04-16

resources:
  infra01-pri-port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ['-', ['infra01', 'pri', { get_param: clustername }]] }
      network: { get_resource: cluster-network }
      security_groups:
        - { get_resource: cluster-sg }
      fixed_ips:
        - subnet: { get_resource: cluster-network-pri }
          ip_address: 10.100.0.51

  infra01:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['.', ['infra01', { get_param: clustername }, 'alces.network']] }
      flavor: { get_param: infra-flavour }
      admin_user: flight
      networks:
          - port: { get_resource: infra01-pri-port }
      block_device_mapping_v2:
        - volume_id: { get_resource: infra01-vol }
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            fqdn: infra01.$clustername.alces.network
            users:
              - default
              - name: flight
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh-authorized-keys:
                  - $key
            write_files:
              - content: |
                  SERVER=$gateway-pri-ip
                  LABEL=infra01
                path: /opt/flight/cloudinit.in
                permissions: '0600'
                owner: root:root
          params:
            $key: { get_param: ssh-key }
            $clustername: { get_param: clustername }
            $gateway-pri-ip: { get_param: gateway-pri-ip }

  infra01-vol:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: solo-image }
      size: 16
