heat_template_version: 2021-04-16

parameters:
  clustername:
    type: string
    label: Cluster Name
    description: The name to give the cluster
    constraints:
      - length: { min: 6, max: 255 }
        description: Cluster name must be between 6 and 255 characters
      - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9\\-_]*$"
        description: Cluster name can contain only alphanumeric characters, hyphens and underscores

  keypair:
    type: string
    label: "SSH keypair to use"
    description: "The ID or name of the keypair to use."
    constraints:
      - custom_constraint: nova.keypair

  cluster-network:
    type: string
    label: Network
    description:  The ID of the network to launch the cluster on.
    constraints:
      - custom_constraint: neutron.network

  cluster-template:
    type: string
    label: Cluster template
    description:  The ID of the cluster template to use.
    constraints:
      - custom_constraint: sahara.cluster_template

  image:
    type: string
    label: Image
    description:  The ID of the image that will be used for cluster deployment.
    constraints:
      - custom_constraint: sahara.image

  hadoop-version:
    type: string
    label: Hadoop version
    description: The version of hadoop running on instances

  plugin-name:
    type: string
    label: Plugin name
    description: The name of the hadoop plugin
    constraints:
      - custom_constraint: sahara.plugin

resources:
  random-chars:
    type: OS::Heat::RandomString
    properties:
      length: 4

  # Unused resources that exist only to satisfy our validation that a network
  # is going to be created.
  unused-route:
    type: OS::Neutron::Router
  unused-network:
    type: OS::Neutron::Net

  cluster:
    type: OS::Sahara::Cluster
    properties:
      cluster_template_id: {get_param: cluster-template}
      default_image_id: {get_param: image}
      hadoop_version: {get_param: hadoop-version}
      key_name: {get_param: keypair}
      name: { list_join: ['-', [{get_param: clustername}, {get_resource: random-chars}]] }
      neutron_management_network: {get_param: cluster-network}
      plugin_name: {get_param: plugin-name}
      # shares: [{"id": String, "path": String, "access_level": String}, {"id": String, "path": String, "access_level": String}, ...]
      use_autoconfig: false
