heat_template_version: 2021-04-16

resources:
  infra01-pri-port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ['-', ['infra01', 'pri', { get_param: clustername }]] }
      network: { get_resource: cluster-network }
      security_groups:
        - { get_resource: cluster-sg }
      fixed_ips:
        - subnet: { get_resource: cluster-network-pri }
          ip_address: 10.100.0.51

  infra01:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['.', ['infra01', { get_param: clustername }, 'alces.network']] }
      flavor: { get_param: infra-flavour }
      key_name: { get_param: key_name }
      admin_user: flight
      networks:
          - port: { get_resource: infra01-pri-port }
      block_device_mapping_v2:
        - volume_id: { get_resource: infra01-vol }
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: ../user_data/infra.yaml }
          params:
            $clustername: { get_param: clustername }
            $nodename: infra01
            $gateway-pri-ip: { get_param: gateway-pri-ip }

  infra01-vol:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: solo-image }
      size: 16
