# This file contains the definitions of the parameters and parameter groups for
# this cluster type.
#
# It contains a `parameters` attribute which is identical to the `parameters`
# attribute used in HOT.
#
# It also contains a `parameter_groups` attribute which is similar to the
# `parameter_groups` attribute used in HOT with a single additional attribute
# `optional`.
#
# The `optional` attribute specifies that a check box or similar should be
# rendered for that parameter group. The parameters contained in the parameter
# group should only be displayed to the user if that check box is selected.
# Cluster builder will use the value of that checkbox to determine which
# optional components to include.

parameter_groups:
  - label: "Cluster parameters"
    description: "Configuration for parameters common across the cluster"
    parameters:
      - clustername
      - solo-image
      # - key_name
      - ssh-key

  - label: "Network settings"
    description: "Configuration for the external and internal cluster networks"
    parameters:
      - external-network
      - network-cidr-pri

  - label: "Gateway parameters"
    description: "Parameters for configuring the gateway"
    parameters:
      - gateway-pri-ip
      - gateway-flavour
      - storage-size

  - label: "Infrastructure node parameters"
    description: "Parameters for configuring infra01 if requested"
    parameters:
      - infra-flavour
    optional:
      label: Create an infrastructure node?
      default: True
      name: "infra"

  - label: "Compute node parameters"
    description: "Parameters for configuring compute nodes if requested"
    parameters:
      - node-flavour
    optional:
      label: Create compute nodes?
      default: True
      name: "nodes"


parameters:
  clustername:
    type: string
    label: Cluster Name
    description: The name to give the cluster
    constraints:
      - length: { min: 6, max: 255 }
        description: Cluster name must be between 6 and 255 characters
      - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9\\-_]*$"
        description: Cluster name can contain only alphanumeric characters, hyphens and underscores

  external-network:
    type: string
    label: External Network Name
    description: The name of the external network to bridge network to
    default: public1
    constraints:
      - custom_constraint: neutron.network

  network-cidr-pri:
    type: string
    label: Primary Nework CIDR
    description: Network CIDR to be used for primary network
    default: '10.100.0.0/16'
    constraints:
      - custom_constraint: net_cidr

  # XXX replace ssh-key with this.
  # key_name:
  #   type: string
  #   label: SSH KeyPair name
  #   description: Name of a KeyPair to enable SSH access to the cluster
  #   constraints:
  #     - custom_constraint: nova.keypair

  ssh-key:
    type: string
    label: SSH Key for Access

  solo-image:
    type: string
    label: Flight Solo Image ID
    default: "Flight Solo 2023.2"
    constraints:
      - custom_constraint: glance.image
      - allowed_values:
        - 'Flight Solo 2023.2'
        - 'Flight Solo 2023.3'
        - 'Flight Solo 2024.1'

  gateway-pri-ip:
    type: string
    label: Gateway Primary IP Address
    default: '10.100.0.1'
    constraints:
      - custom_constraint: ip_addr

  gateway-flavour:
    type: string
    label: Gateway node flavour
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor

  infra-flavour:
    type: string
    label: Infra node flavour
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor

  node-flavour:
    type: string
    label: Compute node flavour
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor

  storage-size:
    type: number
    label: Size of the shared storage disk for NFS in GB
    default: 1024
    constraints:
      - range: { min: 1 }
