#cloud-config
fqdn: $nodename.$clustername.alces.network
users:
  - default
  - name: flight
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - $key
write_files:
  - content: |
      SHAREPUBKEY=true
      AUTOPARSEMATCH=$clustername
      PROFILE_ANSWERS='{ "cluster_type": "openflight-slurm-multinode", "cluster_name": "$clustername", "ipa_use": true, "ipa_domain": "$clustername.alces.network" }'
      AUTOAPPLY="infra: ipa, gateway: login, node: compute"
    path: /opt/flight/cloudinit.in
    permissions: '0600'
    owner: root:root
  - content: |
      DISKID="$sharedstorageid"
      DEVICE="/dev/disk/by-id/virtio-$(echo $DISKID |cut -c -20)"
      mkfs.xfs $DEVICE
      mkdir -p /export
      echo "$DEVICE  /export  xfs  defaults  0 0" >> /etc/fstab
      mount /export
    path: /var/lib/firstrun/scripts/00-sharedstoragemount.bash
    permissions: '0600'
    owner: root:root
  - content: |
      # Generate password for flight user
      FLIGHTPASS=$(cat /dev/urandom |tr -dc _A-Z-a-z-0-9 |head -c 8)
      echo "$FLIGHTPASS" > /root/flight_user_pass.txt
      # Generate secure password for IPA
      IPAPASS=$(cat /dev/urandom |tr -dc _A-Z-a-z-0-9 |head -c 8)
      echo "$IPAPASS" > /root/ipa_admin_pass.txt
      # Ensure Flight Profile uses generated passwords
      /opt/flight/bin/flight profile configure --answers "{ \"cluster_type\": \"openflight-slurm-multinode\", \"default_password\": \"$FLIGHTPASS\", \"ipa_use\": true, \"secure_admin_password\": \"$IPAPASS\"}" --accept-defaults
    path: /var/lib/firstrun/scripts/00-generate-passwords.bash
    permissions: '0600'
    owner: root:root
  - content: |
      until /opt/flight/bin/flight profile list |grep gateway1 |grep -q 'complete' ; do
        echo "Waiting for gateway1 to complete before running..."
        sleep 30
      done
      # Ensure write access to user NFS mounts for cluster users
      chgrp cluster-users /opt/{apps,data}
      chmod 775 /opt/{apps,data}
      # Make Flight Silo use /opt/apps/
      /opt/flight/opt/pdsh/bin/pdsh -g all "sed -i 's,^software_dir:.*,software_dir: /opt/apps,g' /opt/flight/opt/silo/etc/config.yml"
    path: /var/lib/firstrun/scripts/99-post-apply-tweaks.bash
    permissions: '0600'
    owner: root:root
