#cloud-config
fqdn: $nodename.$clustername.alces.network
users:
  - default
  - name: flight
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - $key
write_files:
  - content: |
      SERVER=$gateway-pri-ip
    path: /opt/flight/cloudinit.in
    permissions: '0600'
    owner: root:root
